apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: model-serving-granite
  annotations:
    argocd.argoproj.io/sync-wave: "1"

resources:
  - datasciencecluster.yaml
  - serving-runtime-granite.yaml
  - inference-service-granite.yaml

namespace: redhat-ods-operator

commonLabels:
  snoai-menu-option: "2"
  snoai-config: "model-serving-granite"
