apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: granite-ovms-runtime
  namespace: snoai-system
  labels:
    snoai-menu-option: "2"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    opendatahub.io/template-name: granite-runtime
    opendatahub.io/template-display-name: "Granite Model Runtime (OVMS)"
spec:
  supportedModelFormats:
    - name: granite
      version: "1"
      autoSelect: true

  multiModel: true

  grpcDataEndpoint: port:8085
  grpcEndpoint: port:8085

  containers:
    - name: ovms
      image: quay.io/opendatahub/openvino_model_server:stable
      args:
        - --port=8085
        - --rest_port=8888
        - --model_name={{.Name}}
        - --model_path=/mnt/models
        - --file_system_poll_wait_seconds=0
        - --grpc_bind_address=0.0.0.0
        - --rest_bind_address=0.0.0.0

      resources:
        requests:
          cpu: "2"
          memory: 8Gi
        limits:
          cpu: "4"
          memory: 16Gi

      volumeMounts:
        - name: model-storage
          mountPath: /mnt/models
          readOnly: true

  volumes:
    - name: model-storage
      persistentVolumeClaim:
        claimName: granite-models-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-models-pvc
  namespace: snoai-system
  labels:
    snoai-menu-option: "2"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
